(function(){'use strict';
var $=function(id){return document.getElementById(id);},canvas=$('arena'),ctx=canvas.getContext('2d'),game=null,screen='menu',paused=false,editorTest=false,accumulator=0,lastTime=0,keys={},rebind=null,wasPaused=false,lastHud='',lastPhase='',audio=null,toastTimer,fpsFrames=0,fpsSince=0;
var labels={classic:'Classic',arrows:'Arrows',deatharrows:'Death Arrows',grapple:'Grapple',vtol:'VTOL',football:'Football'};
var descriptions={classic:'Empurre os adversários para fora do mapa. Segure Pesado para resistir às batidas, com menos controle.',arrows:'Segure Especial e use esquerda/direita para girar a mira em 360°. Solte para disparar. A rodinha mostra a recarga.',deatharrows:'Segure Especial, gire a mira com esquerda/direita e solte para disparar. Uma flecha elimina; a rodinha mostra a recarga.',grapple:'Segure Especial para prender o gancho a uma superfície próxima. Solte para liberar; uma batida pode derrubar você.',vtol:'Cima: subir. Esquerda/direita: propulsores laterais. Baixo: impulso invertido. Pesado também funciona.',football:'Leve a bola até o gol adversário. Use Pesado para chutar. Vermelho contra azul.'};
var defaults={layout:'original',quality:1,showFps:true,volume:.25,p1:{id:'p1',name:'Player 1',color:'#dc7885',skin:'face',team:1,bot:false},p2:{id:'p2',name:'Player 2',color:'#6b9ccf',skin:'stripe',team:2,bot:false},twoHumans:false,bots:2,rounds:3,controls:{p1:{left:'ArrowLeft',right:'ArrowRight',up:'ArrowUp',down:'ArrowDown',heavy:'KeyX',special:'KeyZ'},p2:{left:'KeyA',right:'KeyD',up:'KeyW',down:'KeyS',heavy:'KeyF',special:'KeyG'}}};
function clone(v){return JSON.parse(JSON.stringify(v));}function escape(v){return String(v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function read(key,fallback){try{var v=JSON.parse(localStorage.getItem(key));return v==null?fallback:v;}catch(e){return fallback;}}
var prefs=clone(defaults),saved=read('bonk-local-settings',null);if(saved&&typeof saved==='object'){['layout','quality','showFps','volume','twoHumans','bots','rounds'].forEach(function(k){if(saved[k]!=null)prefs[k]=saved[k];});['p1','p2'].forEach(function(k){if(saved[k]){prefs[k].name=String(saved[k].name||defaults[k].name).slice(0,24);if(/^#[0-9a-f]{6}$/i.test(saved[k].color||''))prefs[k].color=saved[k].color;if(['plain','face','stripe','star','ring'].indexOf(saved[k].skin)>=0)prefs[k].skin=saved[k].skin;}if(saved.controls&&saved.controls[k])Object.keys(defaults.controls[k]).forEach(function(a){var v=saved.controls[k][a];if(typeof v==='string'&&/^(Key[A-Z]|Digit[0-9]|Arrow(Up|Down|Left|Right)|Space|Shift(Left|Right))$/.test(v))prefs.controls[k][a]=v;});});}
prefs.layout=prefs.layout==='adapted'?'adapted':'original';prefs.quality=[.75,1,1.5].indexOf(Number(prefs.quality))>=0?Number(prefs.quality):1;prefs.volume=Math.max(0,Math.min(1,Number(prefs.volume)||0));prefs.bots=Math.max(0,Math.min(6,Math.floor(Number(prefs.bots)||0)));prefs.rounds=Math.max(1,Math.min(20,Math.floor(Number(prefs.rounds)||3)));prefs.twoHumans=!!prefs.twoHumans;
var selected=BonkMaps.maps.find(function(m){return m.mode==='classic'&&m.source.historicalVerified;})||BonkMaps.maps[0];
try{prefs.rules=BonkCore.normalizeRules(saved&&typeof saved==='object'?saved.rules:undefined);}catch(e){prefs.rules=BonkCore.normalizeRules();}
var localRules=BonkOptions.mount($('localPhysics'),'local',function(rules){prefs.rules=rules;savePrefs();},toast);
function savePrefs(){try{localStorage.setItem('bonk-local-settings',JSON.stringify(prefs));}catch(e){/* File export remains available for user maps. */}}
function allMaps(){var base=BonkMaps.maps.slice();var local=read('bonk-local-maps',[]);if(Array.isArray(local))local.forEach(function(m){try{m=BonkMaps.validate(m);var at=base.findIndex(function(v){return v.id===m.id;});if(at<0)base.push(m);else base[at]=m;}catch(e){}});return base;}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(function(){$('toast').classList.remove('visible');},3500);}
function keyName(code){return{ArrowLeft:'←',ArrowRight:'→',ArrowUp:'↑',ArrowDown:'↓',Space:'Space',ShiftLeft:'L Shift',ShiftRight:'R Shift'}[code]||String(code).replace(/^Key|^Digit/,'');}
function clearKeys(){keys={};accumulator=0;}
function setLayout(layout){prefs.layout=layout==='adapted'?'adapted':'original';document.body.dataset.layout=prefs.layout;$('layoutButton').textContent=prefs.layout==='original'?'Original':'Adapted';savePrefs();resize();}
function show(next){screen=next;$('playLabel').textContent=BonkRoom.active()?'Online':'Jogo local';document.querySelectorAll('.screen').forEach(function(e){e.classList.toggle('active',e.id===({menu:'menu',lobby:'lobby',lan:'lanLobby',game:'gameHud',editor:'editorScreen'}[next]));});if(next!=='editor')BonkEditor.close();clearKeys();if(next==='lobby')renderLobby();if(next==='menu'){game=null;paused=false;}$('topAvatar').style.background=prefs.p1.color;$('profileButton').textContent=prefs.p1.name;resize();if(next==='game')canvas.focus({preventScroll:true});}
function openModal(title,html){if(screen==='game'&&!BonkRoom.active()){if($('modal').classList.contains('hidden'))wasPaused=paused;paused=true;}else wasPaused=false;clearKeys();$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden');$('modalClose').focus();}
function closeModal(){if(rebind){rebind=null;}var open=!$('modal').classList.contains('hidden');$('modal').classList.add('hidden');if(open&&screen==='game'){paused=wasPaused;$('pauseButton').textContent=BonkRoom.active()?'Sala · Esc':paused?'Continuar · Esc':'Pausar · Esc';canvas.focus({preventScroll:true});}clearKeys();}
function beep(type,intensity){if(!audio||prefs.volume<=0)return;var o=audio.createOscillator(),gain=audio.createGain(),at=audio.currentTime;var freq={hit:170,shoot:500,goal:760,eliminate:100,round:620,start:850,grapple:330}[type];if(!freq)return;o.type=type==='hit'?'triangle':'sine';o.frequency.setValueAtTime(freq,at);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.45),at+.13);gain.gain.setValueAtTime(prefs.volume*.10*(intensity==null?1:Math.max(.15,intensity)),at);gain.gain.exponentialRampToValueAtTime(.0001,at+.16);o.connect(gain);gain.connect(audio.destination);o.start(at);o.stop(at+.17);}
function startAudio(){try{if(!audio){var C=window.AudioContext||window.webkitAudioContext;if(C)audio=new C();}if(audio&&audio.state==='suspended')audio.resume();}catch(e){}}
function drawAvatar(c,p){var x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);BonkRender.disc(x,{x:c.width/2,y:c.height/2,radius:c.width*.35,color:p.color,skin:p.skin},'classic');}
function renderLobby(){
 localRules.set(prefs.rules,false);
 $('modeSelect').value=selected.mode;$('botCount').value=prefs.bots;$('rounds').value=prefs.rounds;$('addPlayer').textContent=prefs.twoHumans?'− Remover segundo jogador':'+ Adicionar segundo jogador';$('playerSetup').innerHTML=['p1'].concat(prefs.twoHumans?['p2']:[]).map(function(id){var p=prefs[id],c=prefs.controls[id];return'<div class="player-card" data-player="'+id+'"><canvas width="76" height="76"></canvas><input class="player-name" aria-label="'+id+' name" maxlength="24" value="'+escape(p.name)+'"><div class="player-controls">'+['left','up','down','right'].map(function(a){return keyName(c[a]);}).join(' ')+' · '+keyName(c.heavy)+' Pesado · '+keyName(c.special)+' Especial</div><input class="player-color" type="color" aria-label="'+id+' colour" value="'+p.color+'"><select class="skin-select" aria-label="'+id+' skin">'+['plain','face','stripe','star','ring'].map(function(s){return'<option'+(p.skin===s?' selected':'')+'>'+s+'</option>';}).join('')+'</select></div>';}).join('');
 $('playerSetup').querySelectorAll('.player-card').forEach(function(card){var id=card.dataset.player;drawAvatar(card.querySelector('canvas'),prefs[id]);card.querySelector('.player-name').oninput=function(e){prefs[id].name=e.target.value.trim().slice(0,24)||defaults[id].name;savePrefs();$('profileButton').textContent=prefs.p1.name;};card.querySelector('.player-color').oninput=function(e){prefs[id].color=e.target.value;drawAvatar(card.querySelector('canvas'),prefs[id]);$('topAvatar').style.background=prefs.p1.color;savePrefs();};card.querySelector('.skin-select').onchange=function(e){prefs[id].skin=e.target.value;drawAvatar(card.querySelector('canvas'),prefs[id]);savePrefs();};});
 $('selectedMapName').textContent=selected.name;$('selectedMapAuthor').textContent='por '+selected.author;$('modeDescription').textContent=descriptions[selected.mode];BonkRender.preview($('mapPreview').getContext('2d'),selected,640,350);
}
function chooseMode(mode){selected=allMaps().find(function(m){return m.mode===mode&&m.source.historicalVerified;})||allMaps().find(function(m){return m.mode===mode;})||selected;renderLobby();}
function quick(){openModal('Escolher modo local','<div class="quick-grid">'+Object.keys(labels).map(function(mode){return'<button class="mode-card" data-mode="'+mode+'"><canvas width="220" height="140"></canvas><strong>'+labels[mode]+'</strong><small>'+descriptions[mode]+'</small></button>';}).join('')+'</div><div class="dialog-actions"><button id="quickCustom">Criar partida</button></div>');$('modalBody').querySelectorAll('[data-mode]').forEach(function(card){var mode=card.dataset.mode,map=allMaps().find(function(m){return m.mode===mode&&m.source.historicalVerified;})||allMaps().find(function(m){return m.mode===mode;});if(map)BonkRender.preview(card.querySelector('canvas').getContext('2d'),map,220,140);card.onclick=function(){closeModal();chooseMode(mode);show('lobby');};});$('quickCustom').onclick=function(){closeModal();show('lobby');};}
function selectMaps(){openModal('Escolher mapa','<div class="map-search"><input id="mapSearch" placeholder="Buscar mapa ou autor" aria-label="Buscar mapa ou autor"><select id="mapModeFilter"><option value="'+selected.mode+'">'+labels[selected.mode]+'</option><option value="all">Todos os modos</option></select></div><div id="mapTiles" class="map-list"></div><div class="dialog-actions"><span id="mapCount"></span><button id="mapsPrev">‹</button><button id="mapsNext">›</button></div>');var page=0;
 function fill(){var q=$('mapSearch').value.toLowerCase(),mode=$('mapModeFilter').value,list=allMaps().filter(function(m){return(mode==='all'||m.mode===mode)&&(m.name+' '+m.author).toLowerCase().indexOf(q)>=0;});var pages=Math.max(1,Math.ceil(list.length/18));page=Math.max(0,Math.min(pages-1,page));$('mapTiles').innerHTML='';list.slice(page*18,page*18+18).forEach(function(m){var b=document.createElement('button');b.className='map-tile'+(m.id===selected.id?' selected':'');b.innerHTML='<canvas width="220" height="135"></canvas><strong>'+escape(m.name)+'</strong><small>'+escape(m.author)+' · '+labels[m.mode]+'</small>';BonkRender.preview(b.querySelector('canvas').getContext('2d'),m,220,135);b.onclick=function(){selected=m;closeModal();renderLobby();};$('mapTiles').appendChild(b);});$('mapCount').textContent=list.length+' maps · '+(page+1)+' / '+pages;$('mapsPrev').disabled=page===0;$('mapsNext').disabled=page>=pages-1;}
 $('mapSearch').oninput=function(){page=0;fill();};$('mapModeFilter').onchange=function(){page=0;fill();};$('mapsPrev').onclick=function(){page--;fill();};$('mapsNext').onclick=function(){page++;fill();};fill();
}
function settings(){var rows=Object.keys(prefs.controls.p1).map(function(a){return'<tr><td>'+({heavy:'Heavy / Kick',special:'Special'}[a]||a[0].toUpperCase()+a.slice(1))+'</td>'+['p1','p2'].map(function(id){return'<td><button class="key-button" data-player="'+id+'" data-key="'+a+'">'+keyName(prefs.controls[id][a])+'</button></td>';}).join('')+'</tr>';}).join('');openModal('Configurações','<div class="settings-row"><label for="layoutSetting">Layout</label><select id="layoutSetting"><option value="original">Original</option><option value="adapted">Adapted</option></select></div><div class="settings-row"><label for="qualitySetting">Gráficos</label><select id="qualitySetting"><option value=".75">Baixo</option><option value="1">Padrão</option><option value="1.5">Alto</option></select></div><div class="settings-row"><label for="volumeSetting">Volume</label><input id="volumeSetting" type="range" min="0" max="1" step=".05"></div><div class="settings-row"><label for="fpsSetting">Mostrar FPS</label><input id="fpsSetting" type="checkbox"></div><table class="control-table"><thead><tr><th>Ação</th><th>Jogador 1</th><th>Jogador 2</th></tr></thead><tbody>'+rows+'</tbody></table><p class="notice">Clique numa tecla e pressione a nova. Esc é usado para pausar. As configurações ficam salvas neste navegador.</p><div class="dialog-actions"><button id="resetControls">Controles padrão</button><button id="settingsDone" class="primary">Concluir</button></div>');$('layoutSetting').value=prefs.layout;$('qualitySetting').value=String(prefs.quality);$('volumeSetting').value=prefs.volume;$('fpsSetting').checked=prefs.showFps;$('layoutSetting').onchange=function(e){setLayout(e.target.value);};$('qualitySetting').onchange=function(e){prefs.quality=Number(e.target.value);resize();savePrefs();};$('volumeSetting').oninput=function(e){prefs.volume=Number(e.target.value);$('soundButton').textContent=prefs.volume>0?'♪':'♫×';savePrefs();};$('fpsSetting').onchange=function(e){prefs.showFps=e.target.checked;savePrefs();};$('modalBody').querySelectorAll('.key-button').forEach(function(b){b.onclick=function(){if(rebind)rebind.button.classList.remove('waiting');rebind={player:b.dataset.player,action:b.dataset.key,button:b};b.textContent='Pressione…';b.classList.add('waiting');};});$('resetControls').onclick=function(){prefs.controls=clone(defaults.controls);savePrefs();settings();};$('settingsDone').onclick=closeModal;}
function profile(id){id=id||'p1';var p=prefs[id];openModal(id==='p1'?'Seu jogador':'Segundo jogador','<label class="line-label">Seu apelido <input id="guestName" maxlength="24" value="'+escape(p.name)+'"></label><label class="line-label">Cor <input id="guestColor" type="color" value="'+p.color+'"></label><div class="dialog-actions"><button id="guestDone" class="primary">Salvar jogador</button></div>');$('guestDone').onclick=function(){p.name=$('guestName').value.trim().slice(0,24)||defaults[id].name;p.color=$('guestColor').value;savePrefs();closeModal();$('profileButton').textContent=prefs.p1.name;$('topAvatar').style.background=prefs.p1.color;if(screen==='lobby')renderLobby();};}
function skins(){openModal('Aparência','<label class="line-label">Jogador <select id="skinPlayer"><option value="p1">Jogador 1</option><option value="p2">Jogador 2</option></select></label><div id="skinChoices" class="quick-grid"></div><label class="line-label">Cor base <input id="skinColor" type="color"></label><div class="dialog-actions"><button id="skinsDone" class="primary">Salvar</button></div>');function fill(){var id=$('skinPlayer').value,p=prefs[id];$('skinColor').value=p.color;$('skinChoices').innerHTML='';['plain','face','stripe','star','ring'].forEach(function(s){var b=document.createElement('button');b.className='mode-card';b.innerHTML='<canvas width="170" height="120"></canvas><strong>'+s+(p.skin===s?' ✓':'')+'</strong>';BonkRender.disc(b.querySelector('canvas').getContext('2d'),{x:85,y:60,radius:32,color:p.color,skin:s},'classic');b.onclick=function(){p.skin=s;savePrefs();fill();};$('skinChoices').appendChild(b);});}$('skinPlayer').onchange=fill;$('skinColor').oninput=function(e){prefs[$('skinPlayer').value].color=e.target.value;savePrefs();fill();};$('skinsDone').onclick=function(){closeModal();$('topAvatar').style.background=prefs.p1.color;if(screen==='lobby')renderLobby();};fill();}
function tutorial(){openModal('Tutorial','<p>Push your opponents off the map. The last player standing wins the round.</p><div class="tutorial-grid"><span class="keycap">← ↑ ↓ →</span><span>Move Player 1. Up also jumps when touching a surface.</span><span class="keycap">X</span><span>Become heavier. You are harder to push, but less manoeuvrable. In Football, kick the ball.</span><span class="keycap">Z</span><span>Segure para carregar a flecha. Esquerda/direita giram a mira em 360°; solte para disparar. A rodinha mostra a recarga. No Grapple, segure para prender o gancho.</span><span class="keycap">W A S D</span><span>Move Player 2. F is Heavy/Kick; G is Special.</span><span class="keycap">Esc</span><span>Pause the local match.</span></div><p class="notice">You can change both players’ keys in Settings. Bots use the same physics and controls as human players.</p>');}
function roster(){var list=[clone(prefs.p1)];if(prefs.twoHumans)list.push(clone(prefs.p2));var colors=['#82b18d','#d1ab6f','#9e88ba','#71adb6','#b88575','#8e9eae'];for(var i=0;i<prefs.bots;i++)list.push({id:'b'+(i+1),name:'Bot '+(i+1),color:colors[i],skin:['plain','ring','face','stripe','star'][i%5],team:i%2+1,bot:true});return list;}
function start(map,test){try{startAudio();closeModal();editorTest=!!test;map=BonkMaps.validate(map||selected);game=BonkCore.create(map,{players:roster(),seed:12345,roundsToWin:prefs.rounds,rules:test?BonkCore.normalizeRules():prefs.rules});paused=false;lastHud='';lastPhase='';show('game');$('pauseButton').textContent='Pausar · Esc';$('gameMapName').textContent=map.name;$('gameMode').textContent=labels[map.mode];$('leaveButton').textContent=editorTest?'Voltar ao editor':'Sair';$('gameHint').textContent=descriptions[map.mode];$('gameHud').dataset.mode=map.mode;}catch(e){toast('Não foi possível iniciar: '+e.message);}}
function winnerName(state,id){if(!id)return'Draw';if(id==='team1')return'Red Team';if(id==='team2')return'Blue Team';var p=state.players.find(function(p){return p.id===id;});return p?p.name:id;}
function hud(state){$('gameHud').dataset.phase=state.phase;$('gameHud').dataset.tick=state.tick;$('gameHud').dataset.round=state.round;var html=state.players.map(function(p){var score=state.scores[p.id]||0;return'<span class="score-chip'+(p.alive?'':' out')+'" style="--player-color:'+p.color+'"><span class="dot"></span>'+escape(p.name)+'<b>'+score+'</b></span>';}).join('');if(html!==lastHud){$('scoreboard').innerHTML=html;lastHud=html;}var text=state.phase==='countdown'?'Round starts in\n'+state.countdown:state.phase==='roundover'?winnerName(state,state.winner)+(state.winner?' wins':''):state.phase==='matchover'?winnerName(state,state.matchWinner)+' wins the match!':'';$('roundAnnouncement').textContent=paused?'Paused':text;if(state.phase==='matchover'&&lastPhase!=='matchover'){if(BonkRoom.active()){openModal('Partida online concluída','<h2>'+escape(winnerName(state,state.matchWinner))+' wins!</h2><div class="dialog-actions"><button id="matchLobby">Sala</button>'+(BonkRoom.isHost()?'<button id="matchAgain" class="primary">Nova partida</button>':'')+'</div>');$('matchLobby').onclick=function(){closeModal();BonkRoom.showLobby();};if(BonkRoom.isHost())$('matchAgain').onclick=function(){closeModal();BonkRoom.start();};}else{paused=true;wasPaused=true;openModal('Match complete','<h2>'+escape(winnerName(state,state.matchWinner))+' wins!</h2><div class="dialog-actions"><button id="matchLobby">'+(editorTest?'Editor':'Lobby')+'</button><button id="matchAgain" class="primary">Play again</button></div>');$('matchLobby').onclick=function(){closeModal();leave(false);};$('matchAgain').onclick=function(){closeModal();start(state.map,editorTest);};}}lastPhase=state.phase;}
function leave(confirm){if(confirm&&game&&game.state().phase!=='matchover'){openModal('Sair da partida?','<p>'+ (BonkRoom.active()?(BonkRoom.isHost()?'Sair encerra a sala para todos.':'Sair desconecta você da sala.'):'Você vai sair desta partida.')+'</p><div class="dialog-actions"><button id="leaveCancel">Cancelar</button><button id="leaveConfirm" class="primary">Ok</button></div>');$('leaveCancel').onclick=closeModal;$('leaveConfirm').onclick=function(){closeModal();leave(false);};return;}if(BonkRoom.active()){BonkRoom.end();return;}game=null;paused=false;closeModal();if(editorTest){editorTest=false;show('editor');BonkEditor.open();}else show('lobby');}
function openEditor(map){game=null;paused=false;show('editor');BonkEditor.open(map?clone(map):undefined);}
function pause(){if(BonkRoom.active()){closeModal();BonkRoom.showLobby();return;}if(!game||game.state().phase==='matchover'||!$('modal').classList.contains('hidden'))return;paused=!paused;clearKeys();$('pauseButton').textContent=paused?'Continuar · Esc':'Pausar · Esc';hud(game.state());}
function resize(){var dpr=Math.min(window.devicePixelRatio||1,1.5)*prefs.quality,w=Math.max(1,window.innerWidth),h=Math.max(1,window.innerHeight);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';canvas.dataset.scale=dpr;}
function inputs(){var result={};['p1'].concat(prefs.twoHumans?['p2']:[]).forEach(function(id){var commands={};Object.keys(prefs.controls[id]).forEach(function(a){commands[a]=!!keys[prefs.controls[id][a]];});result[id]=commands;});return result;}
function loop(time){var delta=Math.min(.15,Math.max(0,(time-lastTime)/1000||0));lastTime=time;fpsFrames++;if(time-fpsSince>1000){$('fps').textContent=prefs.showFps&&screen==='game'?Math.round(fpsFrames*1000/(time-fpsSince))+' FPS':'';fpsSince=time;fpsFrames=0;}var dpr=Number(canvas.dataset.scale)||1,w=canvas.width/dpr,h=canvas.height/dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(BonkRoom.active()){BonkRoom.update(delta,screen==='game'&&$('modal').classList.contains('hidden')&&!document.hidden?inputs().p1:{});if(screen==='game'){var transport=BonkRoom.transport(),networkLabel=labels[$('gameHud').dataset.mode]+' · Online · '+transport;$('gameHud').dataset.transport=transport;if($('gameMode').textContent!==networkLabel)$('gameMode').textContent=networkLabel;}}
 if(game&&screen==='game'){if(!BonkRoom.active()&&!paused&&$('modal').classList.contains('hidden')){accumulator+=delta;while(accumulator>=BonkCore.PARAMS.dt){game.step(inputs());var events=game.state().events;events.forEach(function(e){beep(e.type,e.intensity);});accumulator-=BonkCore.PARAMS.dt;}}var state=game.state();if(state){BonkRender.draw(ctx,state,w,h);hud(state);}}else if(screen!=='editor'){var map=selected,state={map:map,mode:map.mode,bodies:map.bodies,players:[]};for(var i=0;i<4;i++){var a=time*.00012+i*1.9;state.players.push({id:'d'+i,name:'',alive:true,x:map.width*(.2+i*.2)+Math.sin(a)*35,y:map.height*.25+Math.cos(a*1.1)*60,radius:20+i*2,color:['#d77987','#79a9c5','#92ae83','#c5ab7d'][i],skin:['face','stripe','plain','ring'][i],angle:Math.sin(a)*120});}BonkRender.draw(ctx,state,w,h);ctx.fillStyle='rgba(19,31,44,.28)';ctx.fillRect(0,0,w,h);}
 requestAnimationFrame(loop);
}
document.addEventListener('keydown',function(e){if(rebind){e.preventDefault();if(e.code==='Escape'){rebind.button.classList.remove('waiting');rebind.button.textContent=keyName(prefs.controls[rebind.player][rebind.action]);rebind=null;return;}if(!/^(Key[A-Z]|Digit[0-9]|Arrow(Up|Down|Left|Right)|Space|Shift(Left|Right))$/.test(e.code)){toast('Choose a letter, number, arrow, Shift or Space.');return;}var conflict=Object.keys(prefs.controls).some(function(id){return Object.keys(prefs.controls[id]).some(function(a){return!(id===rebind.player&&a===rebind.action)&&prefs.controls[id][a]===e.code;});});if(conflict){toast('That key is already assigned to another action.');return;}prefs.controls[rebind.player][rebind.action]=e.code;rebind.button.textContent=keyName(e.code);rebind.button.classList.remove('waiting');rebind=null;savePrefs();return;}if(e.code==='Escape'){e.preventDefault();if(!$('modal').classList.contains('hidden'))closeModal();else if(screen==='game')pause();return;}if(/^(INPUT|SELECT|TEXTAREA)$/.test(e.target.tagName)||e.target.isContentEditable)return;if(screen==='game'&&$('modal').classList.contains('hidden')){var used=Object.keys(prefs.controls).some(function(id){return Object.keys(prefs.controls[id]).some(function(a){return prefs.controls[id][a]===e.code;});});if(used){e.preventDefault();keys[e.code]=true;}}});document.addEventListener('keyup',function(e){delete keys[e.code];});function suspend(){clearKeys();if(game&&screen==='game'&&!BonkRoom.active()){paused=true;wasPaused=true;$('pauseButton').textContent='Continuar · Esc';}}window.addEventListener('blur',suspend);document.addEventListener('visibilitychange',function(){if(document.hidden)suspend();});window.addEventListener('resize',resize);
document.addEventListener('click',function(e){startAudio();var b=e.target.closest('[data-action]');if(!b||b.closest('#editorContainer'))return;var action=b.dataset.action;if(action==='quick')quick();if(action==='custom')show('lobby');if(action==='menu')show('menu');if(action==='lan-host')BonkRoom.host();if(action==='lan-join')BonkRoom.join();if(action==='editor')openEditor();if(action==='skins')skins();if(action==='tutorial')tutorial();if(action==='friends')toast('Chat e amigos ficam para uma etapa futura. Use Criar sala ou Entrar sala para jogar pela internet.');if(action==='news')openModal('News','<p>Local: two human players, bots, six modes and a map editor.</p><p>Online: até cinco participantes, humanos e bots, abrindo pelo arquivo HTML. Compartilhe o PIN para jogar de redes diferentes.</p>');});
$('settingsButton').onclick=settings;$('layoutButton').onclick=function(){setLayout(prefs.layout==='original'?'adapted':'original');};$('soundButton').onclick=function(){prefs.volume=prefs.volume>0?0:.25;$('soundButton').textContent=prefs.volume>0?'♪':'♫×';savePrefs();};$('profileButton').onclick=function(){profile('p1');};$('modalClose').onclick=closeModal;$('modal').onclick=function(e){if(e.target===$('modal'))closeModal();};$('addPlayer').onclick=function(){prefs.twoHumans=!prefs.twoHumans;savePrefs();renderLobby();};$('botCount').onchange=function(e){prefs.bots=Math.max(0,Math.min(6,Math.floor(Number(e.target.value)||0)));e.target.value=prefs.bots;savePrefs();};$('rounds').onchange=function(e){prefs.rounds=Math.max(1,Math.min(20,Math.floor(Number(e.target.value)||3)));e.target.value=prefs.rounds;savePrefs();};$('modeSelect').onchange=function(e){chooseMode(e.target.value);};$('chooseMap').onclick=selectMaps;$('editSelected').onclick=function(){openEditor(selected);};$('startButton').onclick=function(){start(selected,false);};$('pauseButton').onclick=pause;$('leaveButton').onclick=function(){leave(true);};
BonkEditor.init({container:$('editorContainer'),drawPreview:BonkRender.preview,onTest:function(map){start(map,true);},onSave:function(map){selected=map;toast('Map saved. Export it for a portable copy.');},onBack:function(){try{selected=BonkEditor.getMap();}catch(e){}show('lobby');}});
BonkRoom.init({profile:function(){return clone(prefs.p1);},maps:allMaps,onPreview:function(map){BonkRender.preview($('lanPreview').getContext('2d'),map,640,300);},onError:toast,onEvent:beep,onLobby:function(){closeModal();game=null;paused=false;show('lan');},onExit:function(){closeModal();game=null;paused=false;show('menu');},onGame:function(state){startAudio();clearTimeout(toastTimer);$('toast').classList.remove('visible');closeModal();editorTest=false;paused=false;lastHud='';lastPhase='';game={state:BonkRoom.state};show('game');$('pauseButton').textContent='Sala · Esc';$('leaveButton').textContent='Sair da sala';$('gameMapName').textContent=state.map.name;$('gameMode').textContent=labels[state.mode]+' · Online';$('gameHint').textContent=descriptions[state.mode]+' · '+(state.players.some(function(p){return p.id===BonkRoom.playerId();})?'Seus controles: Player 1.':'Você está assistindo; entra na próxima partida.');$('gameHud').dataset.mode=state.mode;}});
setLayout(prefs.layout);$('soundButton').textContent=prefs.volume>0?'♪':'♫×';show('menu');requestAnimationFrame(loop);
})();
