(function(root){'use strict';
function shape(ctx,b){ctx.beginPath();if(b.shape==='circle')ctx.arc(0,0,b.r,0,Math.PI*2);else if(b.shape==='polygon'&&b.points){b.points.forEach(function(p,i){if(i)ctx.lineTo(p[0],p[1]);else ctx.moveTo(p[0],p[1]);});ctx.closePath();}else ctx.rect(-b.w/2,-b.h/2,b.w,b.h);}
function disc(ctx,p,mode){var r=p.radius||16;ctx.save();ctx.translate(p.x,p.y);ctx.rotate((p.angle||0)*Math.PI/180);
 if(mode==='vtol'){ctx.fillStyle='#37474f';ctx.strokeStyle='#17232a';ctx.lineWidth=2;[-1,1].forEach(function(side){ctx.fillRect(side*r*1.35-5,-5,10,16);ctx.strokeRect(side*r*1.35-5,-5,10,16);if(p.controls&&(p.controls.up||(side<0?p.controls.right:p.controls.left)||p.controls.down)){ctx.fillStyle='#ffb74d';ctx.beginPath();ctx.moveTo(side*r*1.35-4,11);ctx.lineTo(side*r*1.35,25);ctx.lineTo(side*r*1.35+4,11);ctx.fill();ctx.fillStyle='#37474f';}});}
 ctx.shadowColor='rgba(0,0,0,.25)';ctx.shadowBlur=3;ctx.shadowOffsetY=2;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fillStyle=p.color||'#d25258';ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle=p.heavy?'#171c21':'#263238';ctx.lineWidth=p.heavy?4:2.3;ctx.stroke();
 ctx.save();ctx.beginPath();ctx.arc(0,0,r-1,0,Math.PI*2);ctx.clip();
 if(p.skin==='stripe'){ctx.fillStyle='rgba(255,255,255,.75)';ctx.fillRect(-r, -4,r*2,8);}
 if(p.skin==='ring'){ctx.beginPath();ctx.arc(0,0,r*.63,0,Math.PI*2);ctx.lineWidth=4;ctx.strokeStyle='#f5f5f5';ctx.stroke();}
 if(p.skin==='star'){ctx.beginPath();for(var i=0;i<10;i++){var a=-Math.PI/2+i*Math.PI/5,rr=i%2?r*.35:r*.77;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}ctx.closePath();ctx.fillStyle='#fff4b6';ctx.fill();}
 if(p.skin==='face'){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-r*.32,-r*.22,r*.24,0,Math.PI*2);ctx.arc(r*.32,-r*.22,r*.24,0,Math.PI*2);ctx.fill();ctx.fillStyle='#23303b';ctx.beginPath();ctx.arc(-r*.27,-r*.18,r*.1,0,Math.PI*2);ctx.arc(r*.37,-r*.18,r*.1,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#23303b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,r*.12,r*.4,.2,Math.PI-.2);ctx.stroke();}ctx.restore();ctx.restore();
 if(mode==='arrows'||mode==='deatharrows')drawBow(ctx,p);
 if(p.grapple){ctx.strokeStyle='#35434e';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.grapple.x,p.grapple.y);ctx.stroke();ctx.fillStyle='#37474f';ctx.beginPath();ctx.arc(p.grapple.x,p.grapple.y,4,0,Math.PI*2);ctx.fill();}
}
function drawBow(ctx,p){var r=p.radius||16,charge=Math.max(0,Math.min(1,p.charge||0)),cooldown=Math.max(0,Math.min(1,p.cooldown||0)),aiming=p.controls&&p.controls.special;
 if(aiming||charge>0){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.aim||0);ctx.lineCap='round';ctx.lineJoin='round';ctx.globalAlpha=cooldown>0?.55:1;
 var x=r*.65+7,br=Math.max(13,r*.85),tipX=x+Math.cos(1.05)*br,tipY=Math.sin(1.05)*br,pull=x-5-charge*14;
 ctx.beginPath();ctx.arc(x,0,br,-1.05,1.05);ctx.strokeStyle='#233840';ctx.lineWidth=5;ctx.stroke();ctx.strokeStyle='#dcba75';ctx.lineWidth=2.5;ctx.stroke();
 ctx.beginPath();ctx.moveTo(tipX,-tipY);ctx.lineTo(pull,0);ctx.lineTo(tipX,tipY);ctx.strokeStyle='#f9faf4';ctx.lineWidth=1.6;ctx.stroke();
 var end=x+br+19+charge*8;ctx.beginPath();ctx.moveTo(pull,0);ctx.lineTo(end,0);ctx.strokeStyle=modeColor(p);ctx.lineWidth=2;ctx.stroke();
 ctx.beginPath();ctx.moveTo(end+5,0);ctx.lineTo(end-3,-4);ctx.lineTo(end-3,4);ctx.closePath();ctx.fillStyle=ctx.strokeStyle;ctx.fill();ctx.restore();}
 if(cooldown>0||aiming){ctx.save();ctx.translate(p.x+r*.85,p.y+r*.85);var meter=Math.max(5,r*.3);ctx.beginPath();ctx.arc(0,0,meter+2,0,Math.PI*2);ctx.fillStyle='#20353ceb';ctx.fill();ctx.beginPath();ctx.arc(0,0,meter,-Math.PI/2,-Math.PI/2+Math.PI*2*(1-cooldown));ctx.strokeStyle=cooldown>0?'#f3ca7e':'#ccf06a';ctx.lineWidth=2.5;ctx.stroke();ctx.restore();}
}
function modeColor(p){return p.cooldown>0?'#84928c':'#21353d';}
function draw(ctx,state,width,height,opts){opts=opts||{};var map=state.map||state,scale=Math.min(width/map.width,height/map.height),ox=(width-map.width*scale)/2,oy=(height-map.height*scale)/2;ctx.clearRect(0,0,width,height);ctx.fillStyle=opts.letterbox||map.background||'#cfd8dc';ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);ctx.beginPath();ctx.rect(0,0,map.width,map.height);ctx.clip();ctx.fillStyle=map.background||'#cfd8dc';ctx.fillRect(0,0,map.width,map.height);
 (map.zones||[]).forEach(function(z){ctx.fillStyle=z.lethal?'rgba(215,55,65,.16)':'rgba(0,150,136,.10)';ctx.fillRect(z.x-z.w/2,z.y-z.h/2,z.w,z.h);ctx.save();ctx.setLineDash([6,5]);ctx.strokeStyle=z.lethal?'#c4535b':'#58918d';ctx.lineWidth=1;ctx.strokeRect(z.x-z.w/2,z.y-z.h/2,z.w,z.h);ctx.restore();if(opts.editor&&!z.lethal){ctx.fillStyle='#407f80';ctx.font='16px sans-serif';ctx.textAlign='center';ctx.fillText('Force '+(z.forceX||0)+', '+(z.forceY||0),z.x,z.y);}});
 (map.goals||[]).forEach(function(g){ctx.fillStyle=g.team===1?'rgba(214,65,77,.19)':'rgba(57,123,205,.19)';ctx.fillRect(g.x-g.w/2,g.y-g.h/2,g.w,g.h);ctx.strokeStyle=g.team===1?'#c95562':'#548ac2';ctx.lineWidth=3;ctx.strokeRect(g.x-g.w/2,g.y-g.h/2,g.w,g.h);ctx.save();ctx.globalAlpha=.3;ctx.lineWidth=1;for(var x=g.x-g.w/2;x<g.x+g.w/2;x+=12){ctx.beginPath();ctx.moveTo(x,g.y-g.h/2);ctx.lineTo(x,g.y+g.h/2);ctx.stroke();}for(var y=g.y-g.h/2;y<g.y+g.h/2;y+=12){ctx.beginPath();ctx.moveTo(g.x-g.w/2,y);ctx.lineTo(g.x+g.w/2,y);ctx.stroke();}ctx.restore();});
 (state.bodies||map.bodies||[]).forEach(function(b){ctx.save();ctx.translate(b.x,b.y);ctx.rotate((b.angle||0)*Math.PI/180);shape(ctx,b);ctx.fillStyle=b.color||'#607d8b';ctx.shadowColor='rgba(0,0,0,.25)';ctx.shadowBlur=3;ctx.shadowOffsetY=2;ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle='#263238';ctx.lineWidth=2;ctx.stroke();ctx.restore();});
 if(opts.editor)(map.spawns||[]).forEach(function(s,i){ctx.save();ctx.globalAlpha=.65;disc(ctx,{x:s.x,y:s.y,radius:16,color:s.team===2?'#528fca':'#d66a76',skin:'plain'},'classic');ctx.globalAlpha=1;ctx.fillStyle='#33434f';ctx.font='14px sans-serif';ctx.textAlign='center';ctx.fillText('Spawn '+(i+1),s.x,s.y-25);ctx.restore();});
 (state.projectiles||[]).forEach(function(a){ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.angle||0);ctx.strokeStyle=state.mode==='deatharrows'?'#973945':'#3d4e5b';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-12,0);ctx.lineTo(12,0);ctx.stroke();ctx.beginPath();ctx.moveTo(13,0);ctx.lineTo(5,-4);ctx.lineTo(5,4);ctx.closePath();ctx.fill();ctx.restore();});
 if(state.ball){var ball=state.ball;ctx.save();ctx.translate(ball.x,ball.y);ctx.rotate((ball.angle||0)*Math.PI/180);ctx.fillStyle='#f5f5f5';ctx.beginPath();ctx.arc(0,0,ball.r||ball.radius||12,0,Math.PI*2);ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='#263238';ctx.stroke();ctx.fillStyle='#37474f';ctx.beginPath();for(var q=0;q<5;q++){var a=q*Math.PI*2/5;ctx.lineTo(Math.cos(a)*5,Math.sin(a)*5);}ctx.closePath();ctx.fill();ctx.restore();}
 (state.players||[]).forEach(function(p){if(!p.alive)return;disc(ctx,p,state.mode);ctx.save();ctx.fillStyle='#263238';ctx.font='15px BonkFont, sans-serif';ctx.textAlign='center';ctx.fillText(p.name+(p.bot?' [bot]':''),p.x,p.y-(p.radius||16)-10);ctx.restore();});ctx.restore();return{scale:scale,x:ox,y:oy};}
 function preview(ctx,map,w,h){return draw(ctx,{map:map,mode:map.mode,bodies:map.bodies,players:[]},w,h,{editor:true});}
 root.BonkRender={draw:draw,preview:preview,disc:disc};
})(typeof self!=='undefined'?self:this);
